### ISSUE TITLE
ReadMe documentation updates

### ISSUE THREAD

**Issue by rloisell** [bcgov/jag-bcsc-auth-service#13]
One thing missing from the ReadMe documentation is what the service actually does. It explains clearly how to set it up, but not what this microservice provides to those that might want to clone this BCSC AuthN microservice for use within their portals. It should also likely contain some information about dependencies on other services being setup and configured (ie. BC Services Card configuration).

**Comment by adamkroonbcgov** [comment]
Pinging Shaun, Siva, Dan and Alan on this. Thanks @rloisell

**Comment by rloisell** [comment]
Thanks @akroon3r .

CC: @rafaelponcedeleon  - please reach out if you have any questions about what the code does and how it is used.

**Comment by sdevalapurkar-bcgov** [comment]
handled by #14
